// Expo config plugin: pin the Android app locale to Hebrew.
//
// The app forces RTL through I18nManager.forceRTL(), but that flag only
// reaches React Native's own layout engine (Fabric/Yoga). Native views —
// Alert.alert dialogs, pickers, anything AppCompat inflates — take their
// layout direction from the Activity's locale, which follows the device
// (en-US on most dev devices). Result: an alert title with
// textAlignment="viewStart" rendered left-aligned above a right-aligned
// Hebrew message. A per-app locale makes the whole Activity Hebrew/RTL.
//
// `android/` is generated (see .gitignore), so this is re-applied on every
// prebuild like plugins/withReleaseSigning.js.
//
// Two mods:
// 1. MainActivity.onCreate(): AppCompatDelegate.setApplicationLocales("he").
//    It has to run after the first AppCompatActivity attached — before that
//    AppCompat has no context to reach the LocaleManager and the call is a
//    silent no-op — so it lives in MainActivity, not MainApplication.
//    Android 13+ persists the choice in system settings; the guard avoids
//    re-setting (and a possible Activity recreate) on later launches.
// 2. AndroidManifest: opt in to AppCompat's `autoStoreLocales`, which on
//    Android < 13 persists the locale and restores it before onCreate, so
//    the first Activity does not start LTR and then recreate.
const {
  AndroidConfig,
  withAndroidManifest,
  withMainActivity,
} = require("expo/config-plugins");

const MARKER = "// @generated by plugins/withHebrewLocale.js";
const IMPORT_ANCHOR = "import android.os.Bundle\n";
const IMPORTS =
  "import androidx.appcompat.app.AppCompatDelegate\n" +
  "import androidx.core.os.LocaleListCompat\n";
const CALL_ANCHOR = "super.onCreate(null)";
const SNIPPET = `
    ${MARKER}
    // Keep native UI (Alert dialogs, pickers) RTL by making the app Hebrew.
    val hebrewLocales = LocaleListCompat.forLanguageTags("he")
    if (AppCompatDelegate.getApplicationLocales() != hebrewLocales) {
      AppCompatDelegate.setApplicationLocales(hebrewLocales)
    }`;

const LOCALES_SERVICE = "androidx.appcompat.app.AppLocalesMetadataHolderService";

function withHebrewMainActivity(config) {
  return withMainActivity(config, (mod) => {
    if (mod.modResults.language !== "kt") {
      throw new Error("withHebrewLocale only supports a Kotlin MainActivity");
    }
    let src = mod.modResults.contents;
    if (!src.includes(MARKER)) {
      if (!src.includes(IMPORT_ANCHOR) || !src.includes(CALL_ANCHOR)) {
        throw new Error(
          "withHebrewLocale: MainActivity template changed — expected " +
            `"${IMPORT_ANCHOR.trim()}" and "${CALL_ANCHOR}"`
        );
      }
      src = src.replace(IMPORT_ANCHOR, IMPORT_ANCHOR + IMPORTS);
      src = src.replace(CALL_ANCHOR, CALL_ANCHOR + SNIPPET);
    }
    mod.modResults.contents = src;
    return mod;
  });
}

function withAutoStoreLocales(config) {
  return withAndroidManifest(config, (mod) => {
    const app = AndroidConfig.Manifest.getMainApplicationOrThrow(mod.modResults);
    app.service = app.service || [];
    if (!app.service.some((s) => s.$?.["android:name"] === LOCALES_SERVICE)) {
      app.service.push({
        $: {
          "android:name": LOCALES_SERVICE,
          "android:enabled": "false",
          "android:exported": "false",
        },
        "meta-data": [
          { $: { "android:name": "autoStoreLocales", "android:value": "true" } },
        ],
      });
    }
    return mod;
  });
}

module.exports = function withHebrewLocale(config) {
  return withAutoStoreLocales(withHebrewMainActivity(config));
};
