// Expo config plugin: sign release builds with our own keystore.
//
// `android/` is generated (see .gitignore), so any signing setup written
// directly into android/app/build.gradle is lost on `expo prebuild --clean`.
// This plugin re-applies it on every prebuild by appending a Gradle snippet
// that reads credentials/keystore.properties (gitignored; see README).
// When that file is missing the template's debug keystore is used, so
// `expo run:android` keeps working on machines without the credentials.
const { withAppBuildGradle } = require("expo/config-plugins");

const MARKER = "// @generated by plugins/withReleaseSigning.js";

const SNIPPET = `
${MARKER}
def cookEatKeystoreProps = rootProject.file("../credentials/keystore.properties")
if (cookEatKeystoreProps.exists()) {
    def cookEatKeystore = new Properties()
    cookEatKeystoreProps.withInputStream { cookEatKeystore.load(it) }
    android {
        signingConfigs {
            release {
                storeFile new File(cookEatKeystoreProps.parentFile, cookEatKeystore["storeFile"])
                storePassword cookEatKeystore["storePassword"]
                keyAlias cookEatKeystore["keyAlias"]
                keyPassword cookEatKeystore["keyPassword"]
            }
        }
        buildTypes {
            release {
                signingConfig signingConfigs.release
            }
        }
    }
} else {
    logger.warn("withReleaseSigning: credentials/keystore.properties not found; release builds use the debug keystore")
}
`;

module.exports = function withReleaseSigning(config) {
  return withAppBuildGradle(config, (mod) => {
    if (mod.modResults.language !== "groovy") {
      throw new Error("withReleaseSigning only supports a Groovy app/build.gradle");
    }
    if (!mod.modResults.contents.includes(MARKER)) {
      mod.modResults.contents += SNIPPET;
    }
    return mod;
  });
};
